schedulerExtender:
  enabled: true

agent:
  mode: pool
  pool:
    replicas: 2
    nodeSelector: "joulie.io/managed=true"
    shards: 2
    podNodeSelector:
      kubernetes.io/os: linux
  env:
    RECONCILE_INTERVAL: "2s"
    TELEMETRY_CPU_SOURCE: http
    TELEMETRY_CPU_HTTP_ENDPOINT: "http://joulie-telemetry-sim.joulie-system.svc/telemetry/{node}"
    TELEMETRY_CPU_CONTROL: http
    TELEMETRY_CPU_CONTROL_HTTP_ENDPOINT: "http://joulie-telemetry-sim.joulie-system.svc/control/{node}"
    TELEMETRY_GPU_CONTROL: http
    TELEMETRY_GPU_CONTROL_HTTP_ENDPOINT: "http://joulie-telemetry-sim.joulie-system.svc/control/{node}"

operator:
  env:
    RECONCILE_INTERVAL: "3s"
    NODE_SELECTOR: "joulie.io/managed=true"
    OPERATOR_NODE_POWER_SOURCE: http
    OPERATOR_NODE_POWER_HTTP_ENDPOINT: "http://joulie-telemetry-sim.joulie-system.svc/telemetry/{node}"
    ENABLE_FACILITY_METRICS: "true"
    FACILITY_PROMETHEUS_ADDRESS: "http://joulie-telemetry-sim.joulie-system.svc"
