classes:
  - name: gpu-class-1
    matchLabels:
      joulie.io/gpu.product: "NVIDIA-H100-NVL"
    model:
      gpu:
        vendor: nvidia
        product: "NVIDIA H100 NVL"
        count: 8
        idleWattsPerGpu: 60
        maxWattsPerGpu: 400
        minCapWattsPerGpu: 200
        powerModel:
          alphaUtil: 1.0
          betaCap: 1.0
        computeGamma: 1.5
        memoryEpsilon: 0.15
        memoryGamma: 0.9
