apiVersion: v1
kind: Node
metadata:
  name: kwok-node-0
  annotations:
    kwok.x-k8s.io/node: fake
  labels:
    type: kwok
    joulie.io/managed: "true"
    kubernetes.io/role: agent
    feature.node.kubernetes.io/cpu-vendor: GenuineIntel
    feature.node.kubernetes.io/cpu-model.vendor_id: Intel
spec:
  taints:
    - key: kwok.x-k8s.io/node
      value: fake
      effect: NoSchedule
status:
  allocatable:
    cpu: "16"
    memory: "64Gi"
    pods: "110"
  capacity:
    cpu: "16"
    memory: "64Gi"
    pods: "110"
---
apiVersion: v1
kind: Node
metadata:
  name: kwok-node-1
  annotations:
    kwok.x-k8s.io/node: fake
  labels:
    type: kwok
    joulie.io/managed: "true"
    kubernetes.io/role: agent
    feature.node.kubernetes.io/cpu-vendor: AuthenticAMD
    feature.node.kubernetes.io/cpu-model.vendor_id: AMD
spec:
  taints:
    - key: kwok.x-k8s.io/node
      value: fake
      effect: NoSchedule
status:
  allocatable:
    cpu: "16"
    memory: "64Gi"
    pods: "110"
  capacity:
    cpu: "16"
    memory: "64Gi"
    pods: "110"
