apiVersion: joulie.io/v1alpha1
kind: TelemetryProfile
metadata:
  name: sim-http-TARGET_NODE
spec:
  target:
    scope: node
    nodeName: TARGET_NODE
  sources:
    cpu:
      type: http
      http:
        endpoint: http://joulie-telemetry-sim.joulie-sim-demo.svc.cluster.local/telemetry/{node}
        timeoutSeconds: 2
  controls:
    cpu:
      type: http
      http:
        endpoint: http://joulie-telemetry-sim.joulie-sim-demo.svc.cluster.local/control/{node}
        timeoutSeconds: 2
        mode: dvfs
    gpu:
      type: http
      http:
        endpoint: http://joulie-telemetry-sim.joulie-sim-demo.svc.cluster.local/control/{node}
        timeoutSeconds: 2
        mode: powercap
