apiVersion: v1
kind: Namespace
metadata:
  name: joulie-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: joulie-agent
  namespace: joulie-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: joulie-operator
  namespace: joulie-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: joulie-agent
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["joulie.io"]
    resources: ["powerpolicies", "nodepowerprofiles"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: joulie-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: joulie-agent
subjects:
  - kind: ServiceAccount
    name: joulie-agent
    namespace: joulie-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: joulie-operator
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["joulie.io"]
    resources: ["nodepowerprofiles"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: joulie-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: joulie-operator
subjects:
  - kind: ServiceAccount
    name: joulie-operator
    namespace: joulie-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: joulie-agent
  namespace: joulie-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: joulie-agent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: joulie-agent
    spec:
      serviceAccountName: joulie-agent
      hostNetwork: true
      # tolerations:
      #   - operator: Exists
      containers:
        - name: agent
          image: registry.cern.ch/mbunino/joulie/joulie-agent:latest
          imagePullPolicy: Always
          ports:
            - name: metrics
              containerPort: 8080
              protocol: TCP
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: RECONCILE_INTERVAL
              value: 20s
            - name: METRICS_ADDR
              value: :8080
          securityContext:
            privileged: true
            runAsUser: 0
            runAsGroup: 0
            allowPrivilegeEscalation: true
          volumeMounts:
            - name: host-sys
              mountPath: /host-sys
      volumes:
        - name: host-sys
          hostPath:
            path: /sys
            type: Directory
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: joulie-operator
  namespace: joulie-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: joulie-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: joulie-operator
    spec:
      serviceAccountName: joulie-operator
      containers:
        - name: operator
          image: registry.cern.ch/mbunino/joulie/joulie-operator:latest
          imagePullPolicy: Always
          env:
            - name: RECONCILE_INTERVAL
              value: 1m
            - name: NODE_SELECTOR
              value: joulie.io/managed=true
            - name: RESERVED_LABEL_KEY
              value: joulie.io/reserved
            - name: POWER_PROFILE_LABEL
              value: joulie.io/power-profile
            - name: PERFORMANCE_CAP_WATTS
              value: "5000"
            - name: ECO_CAP_WATTS
              value: "120"
---
apiVersion: v1
kind: Service
metadata:
  name: joulie-agent-metrics
  namespace: joulie-system
  labels:
    app.kubernetes.io/name: joulie-agent
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: /metrics
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: joulie-agent
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
