{{- if eq .Values.agent.mode "pool" }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: joulie-agent-pool
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: joulie-agent-metrics
  replicas: {{ .Values.agent.pool.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: joulie-agent
      app.kubernetes.io/component: pool
  template:
    metadata:
      labels:
        app.kubernetes.io/name: joulie-agent
        app.kubernetes.io/component: pool
    spec:
      serviceAccountName: joulie-agent
      {{- with .Values.agent.pool.podNodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: agent
          image: "{{ .Values.agent.image.repository }}:{{ .Values.agent.image.tag }}"
          imagePullPolicy: {{ .Values.agent.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: {{ .Values.agent.service.port }}
              protocol: TCP
          env:
            - name: AGENT_MODE
              value: "pool"
            - name: POOL_NODE_SELECTOR
              value: {{ .Values.agent.pool.nodeSelector | quote }}
            - name: POOL_SHARDS
              value: {{ (default .Values.agent.pool.replicas .Values.agent.pool.shards) | quote }}
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            {{- range $k, $v := .Values.agent.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
{{- end }}
