{{- if .Values.agent.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: joulie-agent-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: joulie-agent
  annotations:
    {{- toYaml .Values.agent.service.annotations | nindent 4 }}
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: joulie-agent
  ports:
    - name: metrics
      port: {{ .Values.agent.service.port }}
      targetPort: metrics
{{- end }}
---
{{- $cm := include "joulie.controllerManager" . | fromYaml }}
{{- if $cm.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: joulie-controller-manager-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: joulie-controller-manager
  annotations:
    {{- toYaml $cm.service.annotations | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: joulie-controller-manager
  ports:
    - name: metrics
      port: {{ $cm.service.port }}
      targetPort: metrics
{{- end }}

