apiVersion: v1
kind: ServiceAccount
metadata:
  name: joulie-agent
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: joulie-operator
  namespace: {{ .Release.Namespace }}

