apiVersion: joulie.io/v1alpha1
kind: NodeTwin
metadata:
  name: worker-1
spec:
  nodeName: worker-1
  profile: eco
  cpu:
    packagePowerCapPctOfMax: 60
  gpu:
    powerCap:
      scope: perGpu
      capPctOfMax: 60
  policy:
    name: queue_aware_v1
  scheduling:
    draining: false
