apiVersion: joulie.io/v1alpha1
kind: NodePowerProfile
metadata:
  name: node-sample
spec:
  nodeName: worker-0
  profile: eco
  cpu:
    packagePowerCapPctOfMax: 60
  gpu:
    powerCap:
      scope: perGpu
      capPctOfMax: 60
  policy:
    name: manual-sample
