apiVersion: v1
kind: Namespace
metadata:
  name: joulie-sim-demo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: joulie-simulator
  namespace: joulie-sim-demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: joulie-simulator
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes"]
    verbs: ["get", "list", "watch", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: joulie-simulator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: joulie-simulator
subjects:
  - kind: ServiceAccount
    name: joulie-simulator
    namespace: joulie-sim-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: joulie-telemetry-sim
  namespace: joulie-sim-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: joulie-telemetry-sim
  template:
    metadata:
      labels:
        app.kubernetes.io/name: joulie-telemetry-sim
    spec:
      serviceAccountName: joulie-simulator
      containers:
        - name: simulator
          image: registry.cern.ch/mbunino/joulie/joulie-simulator:dev0.0.4
          imagePullPolicy: Always
          env:
            - name: SIM_ADDR
              value: ":18080"
            - name: SIM_K8S_POD_WATCH
              value: "true"
            - name: SIM_POLL_INTERVAL
              value: "8s"
            - name: SIM_NODE_SELECTOR
              value: "joulie.io/managed=true"
            - name: SIM_NODE_CLASS_CONFIG
              value: "/etc/joulie-sim/node-classes.yaml"
            - name: SIM_WORKLOAD_TRACE_PATH
              value: "/etc/joulie-sim-trace/trace.jsonl"
          ports:
            - name: http
              containerPort: 18080
          volumeMounts:
            - name: node-classes
              mountPath: /etc/joulie-sim
              readOnly: true
            - name: workload-trace
              mountPath: /etc/joulie-sim-trace
              readOnly: true
      volumes:
        - name: node-classes
          configMap:
            name: joulie-simulator-node-classes
        - name: workload-trace
          configMap:
            name: joulie-simulator-workload-trace
---
apiVersion: v1
kind: Service
metadata:
  name: joulie-telemetry-sim
  namespace: joulie-sim-demo
spec:
  selector:
    app.kubernetes.io/name: joulie-telemetry-sim
  ports:
    - name: http
      port: 80
      targetPort: 18080
