//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CPUCapRange) DeepCopyInto(out *CPUCapRange) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CPUCapRange.
func (in *CPUCapRange) DeepCopy() *CPUCapRange {
	if in == nil {
		return nil
	}
	out := new(CPUCapRange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CPULandmarks) DeepCopyInto(out *CPULandmarks) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CPULandmarks.
func (in *CPULandmarks) DeepCopy() *CPULandmarks {
	if in == nil {
		return nil
	}
	out := new(CPULandmarks)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapState) DeepCopyInto(out *CapState) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapState.
func (in *CapState) DeepCopy() *CapState {
	if in == nil {
		return nil
	}
	out := new(CapState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CatalogExactness) DeepCopyInto(out *CatalogExactness) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CatalogExactness.
func (in *CatalogExactness) DeepCopy() *CatalogExactness {
	if in == nil {
		return nil
	}
	out := new(CatalogExactness)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CatalogKey) DeepCopyInto(out *CatalogKey) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CatalogKey.
func (in *CatalogKey) DeepCopy() *CatalogKey {
	if in == nil {
		return nil
	}
	out := new(CatalogKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlResult) DeepCopyInto(out *ControlResult) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlResult.
func (in *ControlResult) DeepCopy() *ControlResult {
	if in == nil {
		return nil
	}
	out := new(ControlResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlStatus) DeepCopyInto(out *ControlStatus) {
	*out = *in
	if in.CPU != nil {
		in, out := &in.CPU, &out.CPU
		*out = new(ControlResult)
		**out = **in
	}
	if in.GPU != nil {
		in, out := &in.GPU, &out.GPU
		*out = new(ControlResult)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlStatus.
func (in *ControlStatus) DeepCopy() *ControlStatus {
	if in == nil {
		return nil
	}
	out := new(ControlStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUCapRange) DeepCopyInto(out *GPUCapRange) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUCapRange.
func (in *GPUCapRange) DeepCopy() *GPUCapRange {
	if in == nil {
		return nil
	}
	out := new(GPUCapRange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUPowerCap) DeepCopyInto(out *GPUPowerCap) {
	*out = *in
	if in.CapWattsPerGPU != nil {
		in, out := &in.CapWattsPerGPU, &out.CapWattsPerGPU
		*out = new(float64)
		**out = **in
	}
	if in.CapPctOfMax != nil {
		in, out := &in.CapPctOfMax, &out.CapPctOfMax
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUPowerCap.
func (in *GPUPowerCap) DeepCopy() *GPUPowerCap {
	if in == nil {
		return nil
	}
	out := new(GPUPowerCap)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUSlicing) DeepCopyInto(out *GPUSlicing) {
	*out = *in
	if in.Modes != nil {
		in, out := &in.Modes, &out.Modes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUSlicing.
func (in *GPUSlicing) DeepCopy() *GPUSlicing {
	if in == nil {
		return nil
	}
	out := new(GPUSlicing)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InventoryResolution) DeepCopyInto(out *InventoryResolution) {
	*out = *in
	if in.HardwareCatalogKey != nil {
		in, out := &in.HardwareCatalogKey, &out.HardwareCatalogKey
		*out = new(CatalogKey)
		**out = **in
	}
	if in.Exactness != nil {
		in, out := &in.Exactness, &out.Exactness
		*out = new(CatalogExactness)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InventoryResolution.
func (in *InventoryResolution) DeepCopy() *InventoryResolution {
	if in == nil {
		return nil
	}
	out := new(InventoryResolution)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeHardware) DeepCopyInto(out *NodeHardware) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeHardware.
func (in *NodeHardware) DeepCopy() *NodeHardware {
	if in == nil {
		return nil
	}
	out := new(NodeHardware)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeHardware) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeHardwareCPU) DeepCopyInto(out *NodeHardwareCPU) {
	*out = *in
	if in.CapRange != nil {
		in, out := &in.CapRange, &out.CapRange
		*out = new(CPUCapRange)
		**out = **in
	}
	if in.Landmarks != nil {
		in, out := &in.Landmarks, &out.Landmarks
		*out = new(CPULandmarks)
		**out = **in
	}
	if in.Warnings != nil {
		in, out := &in.Warnings, &out.Warnings
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeHardwareCPU.
func (in *NodeHardwareCPU) DeepCopy() *NodeHardwareCPU {
	if in == nil {
		return nil
	}
	out := new(NodeHardwareCPU)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeHardwareCapabilities) DeepCopyInto(out *NodeHardwareCapabilities) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeHardwareCapabilities.
func (in *NodeHardwareCapabilities) DeepCopy() *NodeHardwareCapabilities {
	if in == nil {
		return nil
	}
	out := new(NodeHardwareCapabilities)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeHardwareGPU) DeepCopyInto(out *NodeHardwareGPU) {
	*out = *in
	if in.CapRangePerGPU != nil {
		in, out := &in.CapRangePerGPU, &out.CapRangePerGPU
		*out = new(GPUCapRange)
		**out = **in
	}
	if in.Slicing != nil {
		in, out := &in.Slicing, &out.Slicing
		*out = new(GPUSlicing)
		(*in).DeepCopyInto(*out)
	}
	if in.Warnings != nil {
		in, out := &in.Warnings, &out.Warnings
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeHardwareGPU.
func (in *NodeHardwareGPU) DeepCopy() *NodeHardwareGPU {
	if in == nil {
		return nil
	}
	out := new(NodeHardwareGPU)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeHardwareList) DeepCopyInto(out *NodeHardwareList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodeHardware, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeHardwareList.
func (in *NodeHardwareList) DeepCopy() *NodeHardwareList {
	if in == nil {
		return nil
	}
	out := new(NodeHardwareList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeHardwareList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeHardwareMemory) DeepCopyInto(out *NodeHardwareMemory) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeHardwareMemory.
func (in *NodeHardwareMemory) DeepCopy() *NodeHardwareMemory {
	if in == nil {
		return nil
	}
	out := new(NodeHardwareMemory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeHardwareNetwork) DeepCopyInto(out *NodeHardwareNetwork) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeHardwareNetwork.
func (in *NodeHardwareNetwork) DeepCopy() *NodeHardwareNetwork {
	if in == nil {
		return nil
	}
	out := new(NodeHardwareNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeHardwareQuality) DeepCopyInto(out *NodeHardwareQuality) {
	*out = *in
	if in.Warnings != nil {
		in, out := &in.Warnings, &out.Warnings
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeHardwareQuality.
func (in *NodeHardwareQuality) DeepCopy() *NodeHardwareQuality {
	if in == nil {
		return nil
	}
	out := new(NodeHardwareQuality)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeHardwareSpec) DeepCopyInto(out *NodeHardwareSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeHardwareSpec.
func (in *NodeHardwareSpec) DeepCopy() *NodeHardwareSpec {
	if in == nil {
		return nil
	}
	out := new(NodeHardwareSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeHardwareStatus) DeepCopyInto(out *NodeHardwareStatus) {
	*out = *in
	if in.CPU != nil {
		in, out := &in.CPU, &out.CPU
		*out = new(NodeHardwareCPU)
		(*in).DeepCopyInto(*out)
	}
	if in.GPU != nil {
		in, out := &in.GPU, &out.GPU
		*out = new(NodeHardwareGPU)
		(*in).DeepCopyInto(*out)
	}
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		*out = new(NodeHardwareMemory)
		**out = **in
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(NodeHardwareNetwork)
		**out = **in
	}
	if in.InventoryResolution != nil {
		in, out := &in.InventoryResolution, &out.InventoryResolution
		*out = new(InventoryResolution)
		(*in).DeepCopyInto(*out)
	}
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = new(NodeHardwareCapabilities)
		**out = **in
	}
	if in.Quality != nil {
		in, out := &in.Quality, &out.Quality
		*out = new(NodeHardwareQuality)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeHardwareStatus.
func (in *NodeHardwareStatus) DeepCopy() *NodeHardwareStatus {
	if in == nil {
		return nil
	}
	out := new(NodeHardwareStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeTwin) DeepCopyInto(out *NodeTwin) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeTwin.
func (in *NodeTwin) DeepCopy() *NodeTwin {
	if in == nil {
		return nil
	}
	out := new(NodeTwin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeTwin) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeTwinCPU) DeepCopyInto(out *NodeTwinCPU) {
	*out = *in
	if in.PackagePowerCapWatts != nil {
		in, out := &in.PackagePowerCapWatts, &out.PackagePowerCapWatts
		*out = new(float64)
		**out = **in
	}
	if in.PackagePowerCapPctOfMax != nil {
		in, out := &in.PackagePowerCapPctOfMax, &out.PackagePowerCapPctOfMax
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeTwinCPU.
func (in *NodeTwinCPU) DeepCopy() *NodeTwinCPU {
	if in == nil {
		return nil
	}
	out := new(NodeTwinCPU)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeTwinGPU) DeepCopyInto(out *NodeTwinGPU) {
	*out = *in
	if in.PowerCap != nil {
		in, out := &in.PowerCap, &out.PowerCap
		*out = new(GPUPowerCap)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeTwinGPU.
func (in *NodeTwinGPU) DeepCopy() *NodeTwinGPU {
	if in == nil {
		return nil
	}
	out := new(NodeTwinGPU)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeTwinList) DeepCopyInto(out *NodeTwinList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodeTwin, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeTwinList.
func (in *NodeTwinList) DeepCopy() *NodeTwinList {
	if in == nil {
		return nil
	}
	out := new(NodeTwinList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeTwinList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeTwinPolicy) DeepCopyInto(out *NodeTwinPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeTwinPolicy.
func (in *NodeTwinPolicy) DeepCopy() *NodeTwinPolicy {
	if in == nil {
		return nil
	}
	out := new(NodeTwinPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeTwinScheduling) DeepCopyInto(out *NodeTwinScheduling) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeTwinScheduling.
func (in *NodeTwinScheduling) DeepCopy() *NodeTwinScheduling {
	if in == nil {
		return nil
	}
	out := new(NodeTwinScheduling)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeTwinSpec) DeepCopyInto(out *NodeTwinSpec) {
	*out = *in
	if in.CPU != nil {
		in, out := &in.CPU, &out.CPU
		*out = new(NodeTwinCPU)
		(*in).DeepCopyInto(*out)
	}
	if in.GPU != nil {
		in, out := &in.GPU, &out.GPU
		*out = new(NodeTwinGPU)
		(*in).DeepCopyInto(*out)
	}
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = new(NodeTwinPolicy)
		**out = **in
	}
	if in.Scheduling != nil {
		in, out := &in.Scheduling, &out.Scheduling
		*out = new(NodeTwinScheduling)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeTwinSpec.
func (in *NodeTwinSpec) DeepCopy() *NodeTwinSpec {
	if in == nil {
		return nil
	}
	out := new(NodeTwinSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeTwinStatus) DeepCopyInto(out *NodeTwinStatus) {
	*out = *in
	if in.PowerMeasurement != nil {
		in, out := &in.PowerMeasurement, &out.PowerMeasurement
		*out = new(PowerMeasurement)
		**out = **in
	}
	if in.EffectiveCapState != nil {
		in, out := &in.EffectiveCapState, &out.EffectiveCapState
		*out = new(CapState)
		**out = **in
	}
	if in.ControlStatus != nil {
		in, out := &in.ControlStatus, &out.ControlStatus
		*out = new(ControlStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeTwinStatus.
func (in *NodeTwinStatus) DeepCopy() *NodeTwinStatus {
	if in == nil {
		return nil
	}
	out := new(NodeTwinStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerMeasurement) DeepCopyInto(out *PowerMeasurement) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerMeasurement.
func (in *PowerMeasurement) DeepCopy() *PowerMeasurement {
	if in == nil {
		return nil
	}
	out := new(PowerMeasurement)
	in.DeepCopyInto(out)
	return out
}
