classes:
  - name: intel-default
    matchLabels:
      feature.node.kubernetes.io/cpu-model.vendor_id: Intel
    model:
      baseIdleW: 70
      podW: 110
      dvfsDropWPerPct: 1.6
      raplHeadW: 5
      defaultCapW: 5000
      gpu:
        vendor: nvidia
        product: NVIDIA-L40S
        count: 4
        idleWattsPerGpu: 30
        maxWattsPerGpu: 350
        minCapWattsPerGpu: 200
        powerModel:
          alphaUtil: 1.0
          betaCap: 1.0
  - name: amd-default
    matchLabels:
      feature.node.kubernetes.io/cpu-model.vendor_id: AMD
    model:
      baseIdleW: 80
      podW: 120
      dvfsDropWPerPct: 1.8
      raplHeadW: 5
      defaultCapW: 5000
      gpu:
        vendor: amd
        product: AMD-Radeon-PRO-W7900
        count: 4
        idleWattsPerGpu: 25
        maxWattsPerGpu: 295
        minCapWattsPerGpu: 200
        powerModel:
          alphaUtil: 1.0
          betaCap: 1.0
