apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "joulie-simulator.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "joulie-simulator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "joulie-simulator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "joulie-simulator.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: joulie-simulator
      containers:
        - name: simulator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range $key, $val := .Values.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
            {{- if and .Values.workloadTrace .Values.workloadTrace.content }}
            - name: SIM_WORKLOAD_TRACE_PATH
              value: "/etc/joulie-sim/trace/{{ .Values.workloadTrace.fileName | default "trace.jsonl" }}"
            {{- end }}
          ports:
            - name: http
              containerPort: 18080
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- if .Values.nodeClasses }}
            - name: node-classes
              mountPath: /etc/joulie-sim
              readOnly: true
            {{- end }}
            {{- if and .Values.workloadTrace .Values.workloadTrace.content }}
            - name: workload-trace
              mountPath: /etc/joulie-sim/trace
              readOnly: true
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- if .Values.nodeClasses }}
        - name: node-classes
          configMap:
            name: joulie-simulator-node-classes
        {{- end }}
        {{- if and .Values.workloadTrace .Values.workloadTrace.content }}
        - name: workload-trace
          configMap:
            name: joulie-simulator-workload-trace
        {{- end }}
