apiVersion: v1
kind: Service
metadata:
  name: {{ include "joulie-simulator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "joulie-simulator.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "joulie-simulator.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: 18080
