apiVersion: v1
kind: Service
metadata:
  name: {{ include "joulie-simulator.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "joulie-simulator.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    {{- include "joulie-simulator.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 18080
