apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: joulie-controller-manager
  namespace: default
  labels:
    release: telemetry
spec:
  namespaceSelector:
    matchNames:
      - joulie-system
  selector:
    matchLabels:
      app.kubernetes.io/name: joulie-controller-manager
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
