apiVersion: joulie.io/v1alpha1
kind: NodeTwin
metadata:
  name: stress-ng-demo-profile
spec:
  nodeName: __TARGET_NODE__
  profile: eco
  cpu:
    packagePowerCapWatts: 120.0
  policy:
    name: stress-ng-demo-low
